### ISSUE TITLE
[BUG]: An error occurred while Installation

### ISSUE THREAD

**Issue by Hyg900928** [thecodingmachine/react-native-boilerplate#357] opened 2023-05-10 06:54 UTC
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/19190553/d38a05c5-1d07-43bf-8f59-84c0db2370b1)

An error occurred during the install, what is the reason?

### Version

3.6.5

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

macOs 12.2.1

**Comment by Hyg900928** [comment] 2023-05-10 06:56
![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/19190553/e017e4c9-6001-4cad-83ce-647e77656488)

**Comment by Hyg900928** [comment] 2023-05-10 06:56
Does anyone know what is the reason for this?

**Comment by GeoffreyOlivier** [comment] 2023-05-11 08:09
same error.

**Comment by JeremyDolle** [comment] 2023-05-12 06:03
Duplicate of [#344](https://github.com/thecodingmachine/react-native-boilerplate/issues/344)

**Comment by truongnat** [comment] 2023-05-23 03:55
you can change version ruby to 2.7.7

**Closed** 2023-06-23 19:47 UTC
Labels: :bug: bug
